// Autogenerated via waterline2ts

import {Client} from './Client';

export interface Batch {
   jobs: number;
   client?: Client;  // Association... See Client.ts
   data?: Array;
   details?: Array;
   description?: string;
}
