// Autogenerated via waterline2ts


export interface Charge {
   partnerId: number;
   clientId: number;
   orderId: number;
   amount: number;
   description?: string;
   statementDescription?: string;
   chargeId: string;
}
