// Autogenerated via waterline2ts

import {Directory} from './Directory';
import {Client} from './Client';

export interface ClientLink {
   link: string;
   submissionDate?: string;  // datetime
   client?: Client;  // Association... See Client.ts
   directory?: Directory;  // Association... See Directory.ts
}
