// Autogenerated via waterline2ts

import {ReportingList} from './ReportingList';
import {Client} from './Client';

export interface ClientReportingList {
   client?: Client;  // Association... See Client.ts
   list?: ReportingList;  // Association... See ReportingList.ts
}
