// Autogenerated via waterline2ts


export interface ClientCompetitor {
   businessName: string;
   city: string;
   street1?: string;
   street2?: string;
   state: string;
   postal: string;
   country?: string;  // enum: ["US","GB","CA","AU","DE","NZ"]
   website?: string;
   baseScore?: number;
   currentScore?: number;
   client
   directoryResults?
}
