// Autogenerated via waterline2ts


export interface Directory {
   name: string;
   website: string;
   module: string;
   country: string;  // enum: ["US","GB","CA","AU","DE","NZ"]
   enabled?: boolean;
   frequency: string;  // enum: ["minute","minutes","hour","hours","day","days","week","weeks","month","months","year","years"]
   frequencyInterval?: number;
   pendingFrequency: string;  // enum: ["minute","minutes","hour","hours","day","days","week","weeks","month","months","year","years"]
   pendingFrequencyInterval?: number;
   foundFrequency: string;  // enum: ["minute","minutes","hour","hours","day","days","week","weeks","month","months","year","years"]
   foundFrequencyInterval?: number;
   successFrequency: string;  // enum: ["minute","minutes","hour","hours","day","days","week","weeks","month","months","year","years"]
   successFrequencyInterval?: number;
   reportingList?
}
