// Autogenerated via waterline2ts

import {Directory} from './Directory';
import {ClientCompetitor} from './ClientCompetitor';
import {Client} from './Client';

export interface DirectoryResult {
   nameScore?: number;
   addressScore?: number;
   phoneScore?: number;
   score?: number;
   error?: string;
   queueTime?: string;  // datetime
   startTime?: string;  // datetime
   endTime?: string;  // datetime
   elapsedTime?: number;
   client?: Client;  // Association... See Client.ts
   competitor?: ClientCompetitor;  // Association... See ClientCompetitor.ts
   directoryName: string;
   directory?: Directory;  // Association... See Directory.ts
}
