// Autogenerated via waterline2ts


export interface Job {
   params: Array;
   callback?: string;
   callbackResponse?: string;
   completedAt?: string;  // datetime
   completed?: boolean;
   response?: string;
   success?: boolean;
}
