// Autogenerated via waterline2ts

import {Client} from './Client';
import {Keyword} from './Keyword';

export interface KeywordResult {
   provider: string;  // enum: ["google","googleLocal","bing","bingLocal","yahoo","yahooLocal"]
   data?: Array;
   position?: number;
   error?: string;
   queueTime?: string;  // datetime
   startTime?: string;  // datetime
   endTime?: string;  // datetime
   pending?: boolean;
   reportId?: string;
   keyword?: Keyword;  // Association... See Keyword.ts
   client?: Client;  // Association... See Client.ts
}
