// Autogenerated via waterline2ts

import {Client} from './Client';

export interface Keyword {
   searchTerm: string;
   location?: string;
   provider: string;  // enum: ["google","googleLocal","bing","bingLocal","yahoo","yahooLocal"]
   lastAttempt?: string;  // datetime
   lastSuccess?: string;  // datetime
   errorCount?: number;
   invalid?: boolean;
   client?: Client;  // Association... See Client.ts
}
