// Autogenerated via waterline2ts

import {LegacyOrder} from './LegacyOrder';

export interface LegacyOrderProgress {
   id?: number;
   order?: LegacyOrder;  // Association... See LegacyOrder.ts
   createdAt?: string;  // datetime
   finishedAt?: string;  // datetime
   status?: number;
}
