// Autogenerated via waterline2ts


export interface LegacySocialData {
   id?: number;
   clientId: number;
   lastUpdated?: string;  // datetime
   data?: Array;
   url: string;
   provider: string;
   errors?: Array;
   lastSuccess?: string;  // datetime
}
