// Autogenerated via waterline2ts


export interface LegacyDirectoryData {
   id?: number;
   clientId: number;
   createdAt?: string;  // datetime
   data?: Array;
   directory: string;
   errors?: boolean;
   elapsedTime?: number;
   score?: number;
}
