// Autogenerated via waterline2ts


export interface LegacyClient {
   id?: number;
   name: string;
   owner?: string;
   partner: string;
   street?: string;
   suite?: string;
   hours?: string;
   city: string;
   state: string;
   zipcode: string;
   phone: string;
   fax?: string;
   website?: string;
   email?: string;
   facebook?: string;
   twitter?: string;
   linkedin?: string;
   years?: number;
   description?: number;
   payment?: string;
   services?: string;
   license?: string;
   keyword1?: string;
   keyword2?: string;
   keyword3?: string;
   keyword4?: string;
   keyword5?: string;
   keyword1_location?: string;
   keyword2_location?: string;
   keyword3_location?: string;
   keyword4_location?: string;
   keyword5_location?: string;
   notes?: string;
   hide?: boolean;
   deleted?: string;  // enum: ["false","true"]
   isInactive?: boolean;
   createdAt?: string;  // datetime
   deletedAt?: string;  // datetime
   inactiveAt?: string;  // datetime
   LAT?: number;
   LON?: number;
   custom1?: string;
   custom2?: string;
   custom3?: string;
   custom4?: string;
   custom5?: string;
   status?: string;
}
