// Autogenerated via waterline2ts

import {LegacyProduct} from './LegacyProduct';
import {LegacyOrder} from './LegacyOrder';
import {LegacyClient} from './LegacyClient';
import {LegacyPartner} from './LegacyPartner';

export interface LegacyOrderProduct {
   id?: number;
   partner?: LegacyPartner;  // Association... See LegacyPartner.ts
   client?: LegacyClient;  // Association... See LegacyClient.ts
   order?: LegacyOrder;  // Association... See LegacyOrder.ts
   product?: LegacyProduct;  // Association... See LegacyProduct.ts
   customPackage?: string;
   price?: number;
   priceMaintenance?: number;
   priceRenewal?: number;
   delayMaintenance?: int;
   intervalMaintenance?: int;
   intervalRenewal?: int;
   periodMaintenance?: int;
   isDrip?: string;  // enum: ["false","true"]
   isDisabled?: string;  // enum: ["false","true"]
   isCompleted?: string;  // enum: ["false","true"]
   createdAt?: string;  // datetime
   completedAt?: string;  // datetime
}
