// Autogenerated via waterline2ts


export interface LegacyClientReport {
   id?: number;
   clientId?: number;
   data?: string;
   data_initial?: string;
   type: string;  // enum: ["local","directory","ranking","social","reputation","website","citations","competitor","cancelled"]
}
