// Autogenerated via waterline2ts


export interface LegacyProduct {
   id?: number;
   name?: string;
   description?: string;
   extra?: string;
   priceRetail?: number;
   priceReseller?: number;
   maintenanceInterval?: string;
   productType?: string;
   maintenancePriceRetail?: number;
   maintenancePriceReseller?: number;
   submissionModule?: string;
}
