// Autogenerated via waterline2ts

import {LegacyClient} from './LegacyClient';

export interface LegacyOrder {
   id?: number;
   client?: LegacyClient;  // Association... See LegacyClient.ts
   products?: string;
   createdAt?: string;  // datetime
   startedAt?: string;  // datetime
   publishedAt?: string;  // datetime
   isPaid?: boolean;
   isVerified?: boolean;
   isDrip?: boolean;
   chargeId?: string;
   price?: string;
   schedule?: Array;
}
