// Autogenerated via waterline2ts

import {LegacyClient} from './LegacyClient';
import {LegacyGmbToken} from './LegacyGmbToken';

export interface LegacyGmbTokenClient {
   id?: number;
   token?: LegacyGmbToken;  // Association... See LegacyGmbToken.ts
   client?: LegacyClient;  // Association... See LegacyClient.ts
   createdAt?
}
