// Autogenerated via waterline2ts


export interface LegacyUser {
   id?: number;
   partner?: string;
   firstName?: string;
   lastName?: string;
   email: string;
   password?: string;
   role?: string;  // enum: ["admin","agent","manager","sales","staff"]
}
