// Autogenerated via waterline2ts


export interface LegacyKeywordData {
   id?: number;
   clientId: number;
   lastUpdated?: string;  // datetime
   data?: Array;
   keyword: string;
   provider: string;
   lastSuccess?: string;  // datetime
}
