// Autogenerated via waterline2ts

import {LegacyProduct} from './LegacyProduct';
import {LegacyOrder} from './LegacyOrder';
import {LegacyClient} from './LegacyClient';
import {LegacyPartner} from './LegacyPartner';

export interface LegacyFulfillmentData {
   id?: number;
   partner?: LegacyPartner;  // Association... See LegacyPartner.ts
   client?: LegacyClient;  // Association... See LegacyClient.ts
   order?: LegacyOrder;  // Association... See LegacyOrder.ts
   product?: LegacyProduct;  // Association... See LegacyProduct.ts
   directory?: string;
   status_initial?: string;  // enum: ["not_present","present","claimed"]
   url?: string;
   screenshotUrl?: string;
   status?: string;  // enum: ["initial","existing","added_not_claimed","added_claimed","pending","pin_email","pin_phone","pin_postcard","temporary_problem","not_interested","critical_problem","active"]
   comment?: string;
   commentCustom?: string;
   dateScreenshot?: string;  // datetime
   username?: string;
   password?: string;
   email?: string;
   recoveryPhone?: string;
   recoveryEmail?: string;
   fulfillmentUser?: string;
   dateStarted?: string;  // datetime
   dateEnded?: string;  // datetime
   dateReplaced?: string;  // datetime
   dateCreated?: string;  // datetime
   dateUpdated?: string;  // datetime
   dateVerified?: string;  // datetime
}
