// Autogenerated via waterline2ts

import {LegacyClient} from './LegacyClient';

export interface LegacySubmissionData {
   id?: number;
   directory: string;
   client?: LegacyClient;  // Association... See LegacyClient.ts
   createdAt?: string;  // datetime
   success?: string;  // enum: ["false","true"]
   action?: string;  // enum: ["submit","update","delete","link","claim"]
   url?: string;
   error?: string;
   data?: Array;
}
