// Autogenerated via waterline2ts


export interface Link {
   link: string;
   lastSuccess?: string;  // datetime
   lastActive?: string;  // datetime
   errorCount?: number;
   checkCount?: number;
   statusCode?: number;
   invalid?: boolean;
}
