// Autogenerated via waterline2ts

import {Agency} from './Agency';

export interface ReportingList {
   name: string;
   isGlobal?: boolean;
   isDefault?: boolean;
   agency?: Agency;  // Association... See Agency.ts
   directories?
}
