// Autogenerated via waterline2ts


export interface Resource {
   name: string;
   type: string;
   data: Array;
   limit: number;
   frequency: string;  // enum: ["minute","minutes","hour","hours","day","days","week","weeks","month","months","year","years"]
   frequencyInterval?: number;
   used?: number;
   available?: number;
   lastUsed?: string;  // datetime
   lastReset?: string;  // datetime
   nextReset?: string;  // datetime
}
