// Autogenerated via waterline2ts

import {Client} from './Client';

export interface Social {
   provider: string;  // enum: ["google","twitter","facebook","linkedin","foursquare"]
   link: string;
   lastAttempt?: string;  // datetime
   lastSuccess?: string;  // datetime
   errorCount?: number;
   invalid?: boolean;
   client?: Client;  // Association... See Client.ts
}
