// Autogenerated via waterline2ts

import {Agency} from './Agency';

export interface User {
   name: string;
   email: string;
   password: string;
   salt: string;
   agency?: Agency;  // Association... See Agency.ts
   type: string;  // enum: ["agency","fulfillment","support","admin","sales","agent","manager","internal"]
}
